### ISSUE TITLE
Error: Cannot find module '../lib/cli'

### ISSUE THREAD

**Issue by mcandre** [slang800/editorconfig-tools#25]
When I try to run editorconfig-tools as with the NPM convention `./node_modules/.bin/<program>`, editorconfig-tools fails to find its own lib directory.

Trace:

```
./node_modules/.bin/editorconfig-tools check README.md 

module.js:340
    throw err;
          ^
Error: Cannot find module '../lib/cli'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/apennebaker/Desktop/src/rb-system-with-aliases/node_modules/.bin/editorconfig-tools:8:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

System:

```
$ specs npm:editorconfig-tools node brew os
specs --version
0.19

npm list editorconfig-tools
rb-system-with-aliases@0.0.0 /Users/apennebaker/Desktop/src/rb-system-with-aliases
└── editorconfig-tools@0.1.0 


npm --version
2.7.5

node --version
v0.10.36

brew --version
0.9.5

system_profiler SPSoftwareDataType | grep 'System Version'
    System Software Overview:
      System Version: OS X 10.10.3 (14D136)
```

I wonder why this fails. JSHint, JSLint, and ESLint all work with `./node_modules/.bin/<program>`. Are they structured differently? (https://github.com/jshint/jshint)

**Comment by slang800** [comment]
can't reproduce at all :(

**Comment by mcandre** [comment]
I can't reproduce the problem anymore.
