### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by mcandre** [slang800/editorconfig-tools#31]
When I try to use editorconfig-tools, it mentions what appears to be an API breakage.

Trace:

```
$ node_modules/.bin/editorconfig-tools check lib/comments 

/Users/andrew/go/src/github.com/mcandre/comments/fish/node_modules/editorconfig-tools/node_modules/graceful-fs/node_modules/natives/index.js:102
      fn = runInThisContext(source, nm.filename, true);
           ^
TypeError: needs an unsigned integer 'ms' argument.
    at req_ (/Users/andrew/go/src/github.com/mcandre/comments/fish/node_modules/editorconfig-tools/node_modules/graceful-fs/node_modules/natives/index.js:102:12)
    at Object.req [as require] (/Users/andrew/go/src/github.com/mcandre/comments/fish/node_modules/editorconfig-tools/node_modules/graceful-fs/node_modules/natives/index.js:49:10)
    at Object.<anonymous> (/Users/andrew/go/src/github.com/mcandre/comments/fish/node_modules/editorconfig-tools/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (module.js:450:26)
    at Object.Module._extensions..js (module.js:468:10)
    at Module.load (module.js:350:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:358:17)
    at require (module.js:374:17)
    at Object.<anonymous> (/Users/andrew/go/src/github.com/mcandre/comments/fish/node_modules/editorconfig-tools/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (module.js:450:26)
    at Object.Module._extensions..js (module.js:468:10)
    at Module.load (module.js:350:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:358:17)
    at require (module.js:374:17)

$ node --version
v0.11.6

$ node_modules/.bin/editorconfig-tools -v
0.1.1
```

**Comment by mcandre** [comment]
Workaround: Update to Node.js 4.5
